//This is a temporary file generated by spyglass Lib2V utility from the library
//<mylib_20c.lib>. Do not modify this or use this.
//spyglass xref filename </data/usr/qijiahuan/pmp/rtl_qc/work/lint/workspace/lint/pmp/mygoal/spyglass_spysch/spyglass/example_0.v>
//spyglass xref version SpyGlass_vT-2022.06-1

//spyglass xref lineno 11, -1
`celldefine
module AN2 (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 32, -1
`celldefine
module OR2 (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 53, -1
`celldefine
module IV (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 67, -1
`celldefine
module IVP (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 81, -1
`celldefine
module IVA (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 95, -1
`celldefine
module IVAP (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 109, -1
`celldefine
module IVDA (A, Y, Z);
    input  A;
    output Y;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 130, -1
`celldefine
module IVDAP (A, Y, Z);
    input  A;
    output Y;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 151, -1
`celldefine
module B5I (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 165, -1
`celldefine
module B5IP (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 179, -1
`celldefine
module B4I (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 193, -1
`celldefine
module B4IP (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 207, -1
`celldefine
module ND2 (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 228, -1
`celldefine
module ND2P (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 249, -1
`celldefine
module NR2 (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 270, -1
`celldefine
module NR2P (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 291, -1
`celldefine
module EN (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 312, -1
`celldefine
module ND3 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 340, -1
`celldefine
module ND3P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 368, -1
`celldefine
module NR3 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 396, -1
`celldefine
module NR3P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 424, -1
`celldefine
module AN3 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 452, -1
`celldefine
module OR3 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 480, -1
`celldefine
module ND4 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 515, -1
`celldefine
module ND4P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 550, -1
`celldefine
module NR4 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 585, -1
`celldefine
module ND5 (A, B, C, D, E, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 627, -1
`celldefine
module AO6 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 655, -1
`celldefine
module AO6P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 683, -1
`celldefine
module AO7 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 711, -1
`celldefine
module AO7P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 739, -1
`celldefine
module AO2 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 774, -1
`celldefine
module AO2P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 809, -1
`celldefine
module AO4 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 844, -1
`celldefine
module AO4P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 879, -1
`celldefine
module AO1 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 914, -1
`celldefine
module AO3 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 949, -1
`celldefine
module AO11 (A, B, C, D, E, F, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 998, -1
`celldefine
module AN2P (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1019, -1
`celldefine
module AN3P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1047, -1
`celldefine
module AN4 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1082, -1
`celldefine
module AN4P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1117, -1
`celldefine
module OR2P (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1138, -1
`celldefine
module OR3P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1166, -1
`celldefine
module OR4 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1201, -1
`celldefine
module OR4P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1236, -1
`celldefine
module MUX21H (A, B, S, Z);
    input  A;
    input  B;
    input  S;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1264, -1
`celldefine
module MUX41 (D0, D1, D2, D3, A, B, Z);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1313, -1
`celldefine
module NR5 (A, B, C, D, E, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1355, -1
`celldefine
module ND6 (A, B, C, D, E, F, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1404, -1
`celldefine
module NR6 (A, B, C, D, E, F, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1453, -1
`celldefine
module ND8 (A, B, C, D, E, F, G, H, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    input  G;
    input  H;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1516, -1
`celldefine
module NR8 (A, B, C, D, E, F, G, H, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    input  G;
    input  H;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1579, -1
`celldefine
module EON1 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1614, -1
`celldefine
module EO1 (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1649, -1
`celldefine
module ND5P (A, B, C, D, E, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1691, -1
`celldefine
module NR5P (A, B, C, D, E, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1733, -1
`celldefine
module ND6P (A, B, C, D, E, F, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1782, -1
`celldefine
module NR6P (A, B, C, D, E, F, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1831, -1
`celldefine
module ND8P (A, B, C, D, E, F, G, H, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    input  G;
    input  H;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1894, -1
`celldefine
module NR8P (A, B, C, D, E, F, G, H, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    input  G;
    input  H;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 1957, -1
`celldefine
module NR16 (I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, Z);
    input  I0;
    input  I1;
    input  I2;
    input  I3;
    input  I4;
    input  I5;
    input  I6;
    input  I7;
    input  I8;
    input  I9;
    input  I10;
    input  I11;
    input  I12;
    input  I13;
    input  I14;
    input  I15;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2076, -1
`celldefine
module NR16P (I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, Z);
    input  I0;
    input  I1;
    input  I2;
    input  I3;
    input  I4;
    input  I5;
    input  I6;
    input  I7;
    input  I8;
    input  I9;
    input  I10;
    input  I11;
    input  I12;
    input  I13;
    input  I14;
    input  I15;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2195, -1
`celldefine
module ENP (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2216, -1
`celldefine
module EOP (A, B, Z);
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2237, -1
`celldefine
module EO1P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2272, -1
`celldefine
module EON1P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2307, -1
`celldefine
module AO1P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2342, -1
`celldefine
module AO3P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2377, -1
`celldefine
module AO11P (A, B, C, D, E, F, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2426, -1
`celldefine
module MUX21HP (A, B, S, Z);
    input  A;
    input  B;
    input  S;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2454, -1
`celldefine
module MUX21L (A, B, S, Z);
    input  A;
    input  B;
    input  S;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2482, -1
`celldefine
module MUX21LP (A, B, S, Z);
    input  A;
    input  B;
    input  S;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2510, -1
`celldefine
module MUX31L (D0, D1, D2, A, B, Z);
    input  D0;
    input  D1;
    input  D2;
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2552, -1
`celldefine
module MUX31LP (D0, D1, D2, A, B, Z);
    input  D0;
    input  D1;
    input  D2;
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2594, -1
`celldefine
module MUX41P (D0, D1, D2, D3, A, B, Z);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    input  A;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2643, -1
`celldefine
module MUX21LA (SN, A, S, B, Z);
    input  SN;
    input  A;
    input  S;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2678, -1
`celldefine
module MUX51H (D0, D1, D2, D3, D4, A, B, C, Z);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    input  D4;
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2741, -1
`celldefine
module MUX51HP (D0, D1, D2, D3, D4, A, B, C, Z);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    input  D4;
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2804, -1
`celldefine
module MUX81 (D0, D1, D2, D3, D4, D5, D6, D7, A, B, C, Z);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    input  D4;
    input  D5;
    input  D6;
    input  D7;
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2861, -1
`celldefine
module MUX81P (D0, D1, D2, D3, D4, D5, D6, D7, A, B, C, Z);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    input  D4;
    input  D5;
    input  D6;
    input  D7;
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2945, -1
`celldefine
module AO5 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 2973, -1
`celldefine
module AO5P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3001, -1
`celldefine
module EN3 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3029, -1
`celldefine
module EN3P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3057, -1
`celldefine
module EO3 (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3085, -1
`celldefine
module EO3P (A, B, C, Z);
    input  A;
    input  B;
    input  C;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3113, -1
`celldefine
module AO12 (A, B, C, D, E, F, G, H, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    input  G;
    input  H;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3176, -1
`celldefine
module AO12P (A, B, C, D, E, F, G, H, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    input  E;
    input  F;
    input  G;
    input  H;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3239, -1
`celldefine
module B1I (A, Z);
    input  A;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3256, -1
`celldefine
module MUX21LAP (SN, A, S, B, Z);
    input  SN;
    input  A;
    input  S;
    input  B;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3291, -1
`celldefine
module NR4P (A, B, C, D, Z);
    input  A;
    input  B;
    input  C;
    input  D;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3326, -1
`celldefine
module FD1 (D, CP, Q, QN);
    input  D;
    input  CP;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3367, -1
`celldefine
module FD1P (D, CP, Q, QN);
    input  D;
    input  CP;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3408, -1
`celldefine
module FD1S (D, CP, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3503, -1
`celldefine
module FD1SP (D, CP, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3598, -1
`celldefine
module FD2 (D, CP, CD, Q, QN);
    input  D;
    input  CP;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3658, -1
`celldefine
module FD2P (D, CP, CD, Q, QN);
    input  D;
    input  CP;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3720, -1
`celldefine
module FD2S (D, CP, CD, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  CD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3838, -1
`celldefine
module FD2SP (D, CP, CD, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  CD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 3956, -1
`celldefine
module FD3 (D, CP, CD, SD, Q, QN);
    input  D;
    input  CP;
    input  CD;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4037, -1
`celldefine
module FD3P (D, CP, CD, SD, Q, QN);
    input  D;
    input  CP;
    input  CD;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4118, -1
`celldefine
module FD3S (D, CP, CD, SD, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  CD;
    input  SD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4264, -1
`celldefine
module FD3SP (D, CP, CD, SD, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  CD;
    input  SD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4409, -1
`celldefine
module FD4 (D, CP, SD, Q, QN);
    input  D;
    input  CP;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4469, -1
`celldefine
module FD4P (D, CP, SD, Q, QN);
    input  D;
    input  CP;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4529, -1
`celldefine
module FD4S (D, CP, SD, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  SD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4647, -1
`celldefine
module FD4SP (D, CP, SD, TI, TE, Q, QN);
    input  D;
    input  CP;
    input  SD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4765, -1
`celldefine
module FJK1 (J, K, CP, Q, QN);
    input  J;
    input  K;
    input  CP;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4816, -1
`celldefine
module FJK1P (J, K, CP, Q, QN);
    input  J;
    input  K;
    input  CP;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4867, -1
`celldefine
module FJK1S (J, K, CP, TI, TE, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 4975, -1
`celldefine
module FJK1SP (J, K, CP, TI, TE, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5083, -1
`celldefine
module FJK2 (J, K, CP, CD, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5153, -1
`celldefine
module FJK2P (J, K, CP, CD, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5223, -1
`celldefine
module FJK2S (J, K, CP, CD, TI, TE, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5354, -1
`celldefine
module FJK2SP (J, K, CP, CD, TI, TE, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5485, -1
`celldefine
module FJK3 (J, K, CP, CD, SD, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5576, -1
`celldefine
module FJK3P (J, K, CP, CD, SD, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5667, -1
`celldefine
module FJK3S (J, K, CP, CD, SD, TI, TE, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    input  SD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5825, -1
`celldefine
module FJK3SP (J, K, CP, CD, SD, TI, TE, Q, QN);
    input  J;
    input  K;
    input  CP;
    input  CD;
    input  SD;
    input  TI;
    input  TE;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 5983, -1
`celldefine
module LD1 (D, G, Q, QN);
    input  D;
    input  G;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6032, -1
`celldefine
module LD1P (D, G, Q, QN);
    input  D;
    input  G;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6079, -1
`celldefine
module LD2 (D, GN, Q, QN);
    input  D;
    input  GN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6126, -1
`celldefine
module LD2P (D, GN, Q, QN);
    input  D;
    input  GN;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6173, -1
`celldefine
module LD3 (D, G, CD, Q, QN);
    input  D;
    input  G;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6239, -1
`celldefine
module LD3P (D, G, CD, Q, QN);
    input  D;
    input  G;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6305, -1
`celldefine
module LD4 (D, GN, CD, Q, QN);
    input  D;
    input  GN;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6371, -1
`celldefine
module LD4P (D, GN, CD, Q, QN);
    input  D;
    input  GN;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6435, -1
`celldefine
module B2I (A, Z1, Z2);
    input  A;
    output Z1;
    output Z2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6456, -1
`celldefine
module B2IP (A, Z1, Z2);
    input  A;
    output Z1;
    output Z2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6477, -1
`celldefine
module B3I (A, Z1, Z2);
    input  A;
    output Z1;
    output Z2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6498, -1
`celldefine
module B3IP (A, Z1, Z2);
    input  A;
    output Z1;
    output Z2;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6519, -1
`celldefine
module D24L (A, B, Z0, Z1, Z2, Z3);
    input  A;
    input  B;
    output Z0;
    output Z1;
    output Z2;
    output Z3;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6570, -1
`celldefine
module D24LP (A, B, Z0, Z1, Z2, Z3);
    input  A;
    input  B;
    output Z0;
    output Z1;
    output Z2;
    output Z3;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6621, -1
`celldefine
module FA1 (CI, A, B, S, CO);
    input  CI;
    input  A;
    input  B;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6662, -1
`celldefine
module FA1A (CI, A, B, S, CO);
    input  CI;
    input  A;
    input  B;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6703, -1
`celldefine
module FA1AP (CI, A, B, S, CO);
    input  CI;
    input  A;
    input  B;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6744, -1
`celldefine
module FA1P (CI, A, B, S, CO);
    input  CI;
    input  A;
    input  B;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6785, -1
`celldefine
module HA1 (A, B, S, CO);
    input  A;
    input  B;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6816, -1
`celldefine
module HA1P (A, B, S, CO);
    input  A;
    input  B;
    output S;
    output CO;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6847, -1
`celldefine
module FDS2 (D, CP, CR, Q, QN);
    input  D;
    input  CP;
    input  CR;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6898, -1
`celldefine
module FDS2L (D, CP, CR, LD, Q, QN);
    input  D;
    input  CP;
    input  CR;
    input  LD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 6961, -1
`celldefine
module FDS2LP (D, CP, CR, LD, Q, QN);
    input  D;
    input  CP;
    input  CR;
    input  LD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7024, -1
`celldefine
module FDS2P (D, CP, CR, Q, QN);
    input  D;
    input  CP;
    input  CR;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7075, -1
`celldefine
module FT2 (CP, CD, Q, QN);
    input  CP;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7121, -1
`celldefine
module FT2P (CP, CD, Q, QN);
    input  CP;
    input  CD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7168, -1
`celldefine
module FT4 (CP, SD, Q, QN);
    input  CP;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7215, -1
`celldefine
module FT4P (CP, SD, Q, QN);
    input  CP;
    input  SD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7262, -1
`celldefine
module LD1X4 (D0, D1, D2, D3, Q0, Q1, Q2, Q3, Q0N, Q1N, Q2N, Q3N, G);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    output Q0;
    output Q1;
    output Q2;
    output Q3;
    output Q0N;
    output Q1N;
    output Q2N;
    output Q3N;
    input  G;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7313, -1
`celldefine
module LD1X4P (D0, D1, D2, D3, Q0, Q1, Q2, Q3, Q0N, Q1N, Q2N, Q3N, G);
    input  D0;
    input  D1;
    input  D2;
    input  D3;
    output Q0;
    output Q1;
    output Q2;
    output Q3;
    output Q0N;
    output Q1N;
    output Q2N;
    output Q3N;
    input  G;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7363, -1
`celldefine
module LS1 (D1, C1, D2, C2, Q, QN);
    input  D1;
    input  C1;
    input  D2;
    input  C2;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7421, -1
`celldefine
module LS1P (D1, C1, D2, C2, Q, QN);
    input  D1;
    input  C1;
    input  D2;
    input  C2;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7479, -1
`celldefine
module LSR0 (S, R, Q, QN);
    input  S;
    input  R;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7524, -1
`celldefine
module LSR0P (S, R, Q, QN);
    input  S;
    input  R;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7569, -1
`celldefine
module LSR2 (S, R, G, SD, RD, Q, QN);
    input  S;
    input  R;
    input  G;
    input  SD;
    input  RD;
    output Q;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7650, -1
`celldefine
module BTS4 (A, E, Z);
    input  A;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7676, -1
`celldefine
module BTS4P (A, E, Z);
    input  A;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7702, -1
`celldefine
module BTS5 (A, E, Z);
    input  A;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7728, -1
`celldefine
module BTS5P (A, E, Z);
    input  A;
    input  E;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7754, -1
`celldefine
module FD2TS (D, CP, CD, RD, Z, Q);
    input  D;
    input  CP;
    input  CD;
    input  RD;
    output Z;
    output Q;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7820, -1
`celldefine
module FD2TSP (D, CP, CD, RD, Z);
    input  D;
    input  CP;
    input  CD;
    input  RD;
    output Z;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine

//spyglass xref lineno 7873, -1
`celldefine
module RAM1 (D, WR, WRN, RD, ZN, QN);
    input  D;
    input  WR;
    input  WRN;
    input  RD;
    output ZN;
    output QN;
    parameter SPYGLASS_LIBCELL = 1;
endmodule
`endcelldefine
